version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/download_from_codeartifact.sh
      timeout: 300
      runas: root
    - location: scripts/cleanup.sh
      timeout: 60
      runas: root
    - location: scripts/install_tomcat.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/configure_tomcat.sh
      timeout: 300
      runas: root
    - location: scripts/deploy_war.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 120
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
