version: 0.2

env:
  variables:
    DOMAIN: "project2"
    REPOSITORY: "project2_carepo"
    REGION: "ap-south-1"
    ACCOUNT_ID: "975050380744"
    PACKAGE_NAME: "EcommWebApp"
    PACKAGE_NAMESPACE: "ecomm-app"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "=== Installing build tools ==="
      - yum install -y maven
      - echo "Maven version:"
      - mvn --version
      - echo "AWS CLI version:"
      - aws --version

  pre_build:
    commands:
      - echo "=== Preparing build environment ==="

  build:
    commands:
      - echo "=== Building application ==="
      - echo "Cleaning and compiling..."
      - mvn clean compile
      - echo "Packaging WAR file..."
      - mvn package -DskipTests
      - echo "Build artifacts:"
      - ls -la target/

  post_build:
    commands:
      - echo "=== Packaging for CodeArtifact ==="
      - echo "Creating deployment bundle..."
      - zip -r deployment-bundle.zip target/Ecomm.war appspec.yml scripts/ tomcat-users.xml
      - echo "Bundle contents:"
      - unzip -l deployment-bundle.zip
      - echo "Calculating SHA256 checksum..."
      - ASSET_SHA256=$(sha256sum deployment-bundle.zip | awk '{print $1}')
      - echo "SHA256: $ASSET_SHA256"
      - echo "Getting CodeArtifact authorization token..."
      - CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $DOMAIN --domain-owner $ACCOUNT_ID --region $REGION --query authorizationToken --output text)
      - echo "Publishing to CodeArtifact..."
      - aws codeartifact publish-package-version --domain $DOMAIN --domain-owner $ACCOUNT_ID --repository $REPOSITORY --format generic --namespace $PACKAGE_NAMESPACE --package $PACKAGE_NAME --package-version 1.0.${CODEBUILD_BUILD_NUMBER} --asset-content deployment-bundle.zip --asset-name bundle-${CODEBUILD_BUILD_NUMBER}.zip --asset-sha256 $ASSET_SHA256 --region $REGION
      - echo "=== Successfully published version 1.0.${CODEBUILD_BUILD_NUMBER} to CodeArtifact ==="

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - tomcat-users.xml
  name: CodeDeployArtifacts
