apiVersion: apps/v1
kind: Deployment
metadata:
  name: codedeploy-app
  labels:
    app: codedeploy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codedeploy-app
  template:
    metadata:
      labels:
        app: codedeploy-app
    spec:
      containers:
      - name: codedeploy-app
        image: 975050380744.dkr.ecr.ap-south-1.amazonaws.com/codedeploy
        ports:
        - containerPort: 8080




