apiVersion: v1
kind: Service
metadata:
  name: {{ include "epro.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: epro
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
